name: Create Zip and Attach to Release

on:
  release:
    types: [created]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create zip file
      run: |
        version=${{ github.event.release.tag_name }}
        filename=spell-checker_$(echo $version | sed 's/\./-/g').ankiaddon
        zip -r ${filename} ./* -x "*.git*"
        echo "filename=${filename}" >> $GITHUB_OUTPUT
      id: create-zip

    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./${{ steps.create-zip.outputs.filename }}
        asset_name: ${{ steps.create-zip.outputs.filename }}
        asset_content_type: application/zip
